//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int idProduct { get; set; }
        public Nullable<int> idCategoryProduct { get; set; }
        public string idUserCreated { get; set; }
        public string idUserModified { get; set; }
        public Nullable<System.DateTime> timeCreated { get; set; }
        public Nullable<System.DateTime> timeModified { get; set; }
        public string title { get; set; }
        public string alias { get; set; }
        public string content { get; set; }
        public string note { get; set; }
        public string description { get; set; }
        public Nullable<int> published { get; set; }
        public string image { get; set; }
        public string tags { get; set; }
        public Nullable<int> stt { get; set; }
        public Nullable<int> deleted { get; set; }
        public string feature { get; set; }
        public string metadescription { get; set; }
        public string metakewords { get; set; }
        public string author { get; set; }
        public string robots { get; set; }
        public string gra0w20_specification { get; set; }
        public string gra0w20_technical { get; set; }
        public string gra0w30_specification { get; set; }
        public string gra0w30_technical { get; set; }
        public string gra0w40_specification { get; set; }
        public string gra0w40_technical { get; set; }
        public string gra0w50_specification { get; set; }
        public string gra0w50_technical { get; set; }
        public string gra5w20_specification { get; set; }
        public string gra5w20_technical { get; set; }
        public string gra5w30_technical { get; set; }
        public string gra5w30_specification { get; set; }
        public string gra5w40_specification { get; set; }
        public string gra5w40_technical { get; set; }
        public string gra5w50_specification { get; set; }
        public string gra5w50_technical { get; set; }
        public string gra10w30_specification { get; set; }
        public string gra10w30_technical { get; set; }
        public string gra10w40_specification { get; set; }
        public string gra10w40_technical { get; set; }
        public string gra15w40_specification { get; set; }
        public string gra15w40_technical { get; set; }
        public string gra15w50_specification { get; set; }
        public string gra15w50_technical { get; set; }
        public string gra20w50_specification { get; set; }
        public string gra20w50_technical { get; set; }
        public string gra75w140_specification { get; set; }
        public string gra75w140_technical { get; set; }
        public string gra75w90_specification { get; set; }
        public string gra75w90_technical { get; set; }
        public string gra80w90_specification { get; set; }
        public string gra80w90_technical { get; set; }
        public string gra85w140_specification { get; set; }
        public string gra85w140_technical { get; set; }
    }
}
